<a href="https://colab.research.google.com/github/IsaacOZ11/ACT/blob/main/Isaac_Numpy_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy.core.multiarray import zeros
import numpy as np

aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)


aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))


tmp=np.zeros([4,4])
print(tmp)


tmp=np.full([4,4],5)
print(tmp)


tmp=np.eye(4,4)
print(tmp)

print("-------------------------")
tmp=np.ones([4,4])
print(tmp)

print(tmp.shape)

[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [2]:
tmp=10*np.random.random([3,3])
print(tmp)

[[8.16817332 7.24683855 4.55277248]
 [2.2894255  7.42769843 7.44560324]
 [6.66063555 5.66830458 9.8969471 ]]


In [3]:
print(tmp[:2,:2])

[[8.16817332 7.24683855]
 [2.2894255  7.42769843]]


In [ ]:
print(tmp[:2,1:3])

[[6.45954779 0.04573917]
 [1.1309072  5.13337449]]


In [4]:
print(tmp[2,2])

9.896947104429382


In [5]:
tmp=10*np.random.random([3,3])
print(tmp)

[[1.81471545 5.97832131 8.23221795]
 [2.6693528  8.35456457 4.83614911]
 [4.126551   3.97788146 6.01855074]]


In [6]:
mask=tmp>5
print(tmp[mask])

[5.97832131 8.23221795 8.35456457 6.01855074]


In [7]:
mask=(tmp>=2) & (tmp<=4)
print(tmp[mask])

[2.6693528  3.97788146]


In [8]:
np = np.random.randint(0,100, (4,4))

np = np[np % 2 == 0]
print(np)

[42 36 60 76 20 40 14 48 66]


In [9]:
import numpy as np

# Create an array with integer values batween 1 and 10
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print("adding numbers")
print(a+b)
print("substracting numbers")
print(a-b)

print(np.add(a,b))
print(np.multiply(a,b))

[[ 2  1  4  8]
 [ 6  6  1  9]
 [ 7 10  1 10]]
[[ 6 10  9 10]
 [ 2  2 10  1]
 [ 4 10  5  1]]
(3, 4)
(3, 4)
adding numbers
[[ 8 11 13 18]
 [ 8  8 11 10]
 [11 20  6 11]]
substracting numbers
[[-4 -9 -5 -2]
 [ 4  4 -9  8]
 [ 3  0 -4  9]]
[[ 8 11 13 18]
 [ 8  8 11 10]
 [11 20  6 11]]
[[ 12  10  36  80]
 [ 12  12  10   9]
 [ 28 100   5  10]]


In [10]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[1 9 1]
 [3 1 2]]
[[6 1 7 3]
 [7 2 4 6]
 [9 2 8 6]]
[[78 21 51 63]
 [43  9 41 27]]
[[78 21 51 63]
 [43  9 41 27]]


In [11]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[3 4]
 [8 3]]
[[3 8]
 [4 3]]


In [12]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)

print(c.shape)
print("----------------------")
print(c)

(4, 3)
(3,)
[[ 1  7 10]
 [10  6  7]
 [ 4 10  1]
 [ 3  5  6]]
[1 0 2]
(4, 3)
----------------------
[[ 2  1  4]
 [ 8  6  6]
 [ 1  9  7]
 [10  1 10]]


In [13]:
for i in range(4):
  c[i,:]=a[i,:]+b

print (a)
print (b)
print (c)

c=a+b
print(c)

[[ 1  7 10]
 [10  6  7]
 [ 4 10  1]
 [ 3  5  6]]
[1 0 2]
[[ 2  7 12]
 [11  6  9]
 [ 5 10  3]
 [ 4  5  8]]
[[ 2  7 12]
 [11  6  9]
 [ 5 10  3]
 [ 4  5  8]]


In [14]:
a=np.array([1,2,3])

print(a)

tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [15]:
a=np.random.randint(0,10,size=(6,6))
print(a)
aux=np.mean(a)
print(aux)



print(a.mean(axis=1))

[[0 2 6 7 9 4]
 [4 2 8 8 1 0]
 [2 1 4 5 7 7]
 [6 6 1 5 1 0]
 [6 2 1 4 7 6]
 [8 7 1 9 2 2]]
4.194444444444445
[4.66666667 3.83333333 4.33333333 3.16666667 4.33333333 4.83333333]
