<a href="https://colab.research.google.com/github/IsaacOZ11/ACT/blob/main/Isaac_Exploring_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [1]:
# Import numpy as np and see the version
import numpy as np
print(np.__version__)
# your code here
pass

1.23.5


In [2]:
# Create a 1D array of numbers from 0 to 9
# your code here
my_array = np.arange(10)
# Print the array
print(my_array)
pass

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

# Print the modified vector
print(random_vector)
pass

[0.15477826 0.91220883 0.68001242 0.24306339 0.54720206 0.5175512
 0.28571847 0.16047918 0.         0.69780889]


In [4]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Create the array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Access and print the element at the second row (index 1) and the third column (index 2)
element = arr[1, 2]
# Print the element
print(element)
pass

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
# Create the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use array slicing to extract the elements [3, 4, 5]
subset = arr[2:5]

# Print the subset
print(subset)
pass

[3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Use negative indexing to extract the last 4 elements
subset = arr[-4:]
# Print the subset
print(subset)
pass

[4 5 6 7]


In [7]:
# Create a 3×3 numpy array of all True’s
# your code here
true_array = np.full((3, 3), True)

# Print the array
print(true_array)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extract all odd numbers from arr
# your code here

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Extract all odd numbers from the array
odd_numbers = arr[arr % 2 != 0]
# Print the extracted odd numbers
print(odd_numbers)
pass

[1 3 5 7 9]


In [9]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
my_vector = np.arange(10, 50)
print(my_vector)

pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Reverse a vector (first element becomes last)
# Create a vector
my_vector = np.array([1, 2, 3, 4, 5])
# Reverse the vector
reversed_vector = my_vector[::-1]
print(reversed_vector)

pass

[5 4 3 2 1]


In [11]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
random_array = np.random.randint(low=1, high=100, size=(10, 10))

# Find the minimum and maximum values
minimum_value = np.min(random_array)
maximum_value = np.max(random_array)

# Print the array and the minimum and maximum values
print("Random Array:")
print(random_array)
print("\nMinimum Value:", minimum_value)
print("Maximum Value:", maximum_value)

pass

Random Array:
[[ 8 64 20 64 55 99 97 11 17 38]
 [71 20 60 72 59  7 36 80 80 48]
 [15 54 52 28 81 77 41 14 88 91]
 [78 22  6 44 50 12 91 42  6 23]
 [ 3 76 83 72 70 89 91 18 70 73]
 [ 6 21 65 70 13 59 29 74 25 20]
 [10 93 58 62 34 37 52 31 94 74]
 [67 20 16 14 87 73 46 12 41 51]
 [57 56 82 53 87 86 28 90 34 59]
 [21 39 86 62 24 63 72 34 57 37]]

Minimum Value: 3
Maximum Value: 99


In [12]:
# Create a 3x3x3 array with random values
# Create a 3x3x3 array with random integer values between 1 and 100
random_int_3d_array = np.random.randint(low=1, high=100, size=(3, 3, 3))
print(random_int_3d_array)

pass

[[[69 40 45]
  [72 19 60]
  [21 76 16]]

 [[50  7  5]
  [ 8  3 98]
  [25 68  5]]

 [[63 88 61]
  [19 14 70]
  [43 34 91]]]


In [13]:
# Replace all odd numbers in arr with -1
# your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace all odd numbers with -1
arr[arr % 2 != 0] = -1

print(arr)

pass

[-1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Create an array of type float
float_array = np.array([1.0, 2.5, 3.7, 4.2], dtype=float)

print(float_array)
print("Data Type:", float_array.dtype)

pass

[1.  2.5 3.7 4.2]
Data Type: float64


In [15]:
# Convert a 1D array to a 2D array with 2 rows

# Create a 1D array
my_1d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convert the 1D array to a 2D array with 2 rows
my_2d_array = np.reshape(my_1d_array, (2, -1))

# Print the 2D array
print(my_2d_array)

pass

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

# Find common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

# Print
print("Z1:", Z1)
print("Z2:", Z2)
print("Common Values:", common_values)

pass

Z1: [2 7 5 1 1 0 4 7 8 2]
Z2: [7 9 8 7 3 9 2 1 6 7]
Common Values: [1 2 7 8]


In [17]:
#  Consider two random array A and B, check if they are equal
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

# Print the arrays and the result of the equality check
print("Array A:", A)
print("Array B:", B)
print("Arrays are equal:", are_equal)


pass

Array A: [0 1 0 1 1]
Array B: [1 1 0 1 0]
Arrays are equal: False


In [18]:
# Stack arrays a and b vertically
# your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays a and b vertically
stacked_array = np.vstack((a, b))

# Print the stacked array
print(stacked_array)

pass

[[1 2 3]
 [4 5 6]]


In [19]:
# Stack the arrays a and b horizontally.
# your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays a and b horizontally
stacked_array = np.hstack((a, b))

# Print the stacked array
print(stacked_array)

pass

[1 2 3 4 5 6]


In [20]:
# Get all items between 5 and 10 from array tmp.
# your code here
#import numpy as np
#tmp = np.arange(15)

# Create a NumPy array
tmp = np.array([1, 3, 7, 8, 5, 6, 2, 9, 4, 10])

# Get all items between 5 and 10
result = tmp[(tmp >= 5) & (tmp <= 10)]
print(result)

# pass

[ 7  8  5  6  9 10]


In [21]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# your code here
#import numpy as np
#def maxx(x, y):
#    """Get the maximum of two items"""
#    if x >= y:
#        return x
#    else:
#        return y
#maxx(1, 5)

def pair_max(a, b):
    # Use numpy.maximum to find the element-wise maximum between a and b
    result = np.maximum(a, b)
    return result

# Test the function with NumPy arrays
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

output = pair_max(a, b)
print(output)



[6 7 9 8 9 7 5]


In [22]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
# your code here

# Create a NumPy array
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

# Print the modified array
print(arr)

pass


[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

import numpy as np

# Create a 2D array of shape 5x3 with random decimal numbers between 5 and 10
random_array = np.random.uniform(5, 10, size=(5, 3))

# Print the generated array
print(random_array)


[[8.00065601 5.71547036 8.55980945]
 [8.88751607 9.78572421 8.1320678 ]
 [9.41713823 6.20203176 7.33286294]
 [8.65991024 5.99285455 5.8234166 ]
 [5.63663679 5.58786273 6.92278533]]
